apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemicroservice
spec:
  selector:
    matchLabels:
      app: timemicroservice
  template:
    metadata:
      labels:
        app: timemicroservice
    spec:
      containers:
      - name: timemicroservice
        image: diegopacheco/time-microservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
