apiVersion: v1
kind: Service
metadata:
  name: timemicroservice
  labels:
    app: timemicroservice
    role: service
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: timemicroservice
    role: service
    tier: backend